### ISSUE TITLE
Getting the diff to a reference (HEAD)

### ISSUE THREAD

**Issue by jhlgns** [SkinnyMind/libgit2dart#16]
Hello again! I am trying to get a diff to the HEAD reference.
However, `repo.diff(...)` only accepts trees as arguments.
Is this possible with libgit2dart? Thanks!

PS.: It would be very cool to get be able to contact you over [gitter](https://gitter.im) for example - or other platforms for small things like this, maybe you could create a room for `libgit2dart`?

**Comment by SkinnyMind** [comment]
Hey there! What are you trying to get the diff of? With `repo.diff()` You can compare index and workdir, index and tree, tree and workdir, tree and tree. And each class (Index, Tree, Blob) also have separate diff methods.

And i'm not really big on social media, but you can contact me at skinny.mind@gmail.com for small things.

**Comment by SkinnyMind** [comment]
And i'd recommend looking at tests, since it's usually the best place to get the idea of how api works.
