### ISSUE TITLE
Usage in Dart app without flutter

### ISSUE THREAD

**Issue by Matslom** [SkinnyMind/libgit2dart#61]
Hello,
I'm new to Dart, maybe there is something that I'm missing.
I have pure Dart app and wanted to require your package. The readme says that this package should work in dart but because of 
```
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"
```
I'm not able to update dependencies because my app is not a flutter app.

Is there a way that I can add this package to app that is not a flutter app?

**Comment by SkinnyMind** [comment]
I am able to update dependencies in dart app without any problem.

What i did was:
- Created new dart cli application with `dart create gittest`
- Added libgit2dart as dependency in pubspec.yaml:
  ```yaml
  dependencies:
    libgit2dart: ^1.1.0
  ```
- Got dependencies with `dart pub get` (if you are using VSCode after editing pubspec.yaml and saving it, it should also get dependencies without any problem)

**Comment by Matslom** [comment]
Thanks for the reply.
So, thats odd. Its almost clear dart project. I have pubspec like this
```
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  libgit2dart: ^1.1.0
```
and after `dart pub get`
I'm getting 
```
Resolving dependencies...
Because globox depends on libgit2dart >=1.1.0 which requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `dart pub get`.
```
My dart version
```
dart --version
Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "macos_x64"
```

**Comment by SkinnyMind** [comment]
And what happens if you run `flutter pub get`?

**Comment by Matslom** [comment]
Currently I don't have flutter installed so i cannot check that. 
I've searched for some libs at pub.dev that are listed as for Dart and Flutter, and every package have listed only sdk in environment section.
If I understand correctly what says https://dart.dev/tools/pub/pubspec#sdk-constraints I have to install flutter to use that package.

**Comment by SkinnyMind** [comment]
Ok, I thought you have Flutter installed. I guess you have to use `flutter pub get` even if you want to use it with Dart cli application.
It's probably related to https://github.com/dart-lang/pub/issues/2606, since package also provides support for Flutter applications.

Please reply with result, after installing Flutter. I believe that'll fix the issue.

**Comment by Matslom** [comment]
I don't really need flutter for now.
So instead of installing flutter, I've forked repo, removed flutter dependency and added
```
dependency_overrides:
  libgit2dart:
    git:
      url: https://github.com/Matslom/libgit2dart
```
to the pubspec. Looks like it's working fine.

**Comment by SkinnyMind** [comment]
Sure, that'll work :)

As a side note, if you'll install Flutter, the Dart SDK is bundled with it, so no need to have separate installation of Dart.

I'm closing issue, since it appears to be resolved.
