### ISSUE TITLE
How can I output real-time progress when I'm pushing? Instead of printing all the progress at once after the push

### ISSUE THREAD

**Issue by Lojii** [SkinnyMind/libgit2dart#73]
ReceivePort receivePort = ReceivePort();
    sendPort.send(receivePort.sendPort);
    receivePort.listen((params) {
      ...
      try{
      	...
        var keypair = Keypair(username: username,pubKey: sshKey.publicKeyPath ,privateKey: sshKey.privateKeyPath,passPhrase: sshKey.passPhrasePath);
        var callbacks = Callbacks(credentials: keypair,
            sidebandProgress: (progress){
              sendPort.send(progress);
              print(progress);
            }
        );
        remote.push(refspecs: ['refs/heads/master'],callbacks: callbacks);
        print('push to ${remote.url} success !');
        remote.free();
        sendPort.send('success');
      }catch(e){
        print('push error:$e');
        ...
      }
    });

**Comment by SkinnyMind** [comment]
Hi, what does `stdout.write(progress)` instead of `print(progress)` produce?

**Comment by Lojii** [comment]
The result is the same . 
By the way, This code runs on iOS devices. Run asynchronously using Isolate.
I'm trying to show the real-time progress of push on the screen.

**Comment by SkinnyMind** [comment]
Is progress displayed in "real-time" when you don't use isolate?

**Comment by SkinnyMind** [comment]
Can you confirm, please, that for example, using that sidebandProgress callback in Repository.clone(...) provides you the result you want?
