### ISSUE TITLE
Failed to load dynamic library

### ISSUE THREAD

**Issue by suxoikorm** [SkinnyMind/libgit2dart#77]
When I try to check that Libgit2 is installed (with print(Libgit2.version)), i get an error:
```
Failed to open the library. Make sure that libgit2 library is bundled with the application.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library 'flutter_app_repo_path\.dart_tool\libgit2\windows\libgit2-1.5.0.dll': error code 126
```

This is a Flutter Windows project.
I tried dart run libgit2dart:setup but it did not help.

OS: Windows 11 22621.819
Flutter: 3.3.8
Dart: 2.18.4

**Comment by SkinnyMind** [comment]
Can you, please, provide link to example repository with the problem?

**Comment by suxoikorm** [comment]
> Can you, please, provide link to example repository with the problem?

Sure, https://github.com/suxoikorm/libgit2dart_error

**Comment by suxoikorm** [comment]
@SkinnyMind, It worked. Thank you! I will close the issue.
`flutter: Libgit2 version: 1.5.0`

**Comment by SkinnyMind** [comment]
Glad I could help!
