### ISSUE TITLE
The setup didn't copy the libgit2.x.x.dylib to .dart_tools folder on MacOS

### ISSUE THREAD

**Issue by EbenZhang** [SkinnyMind/libgit2dart#80]
Due to the issue in this library https://github.com/google/pub_cache/issues/47 unable to find the pub-cache on MacOS.

Error is 

```
Copying libgit2 for macos
Unhandled exception:
Null check operator used on a null value
#0      copyLibrary (file:///Users/.../.pub-cache/hosted/pub.dev/libgit2dart-1.2.1/bin/setup.dart:42:27)
```

**Comment by SkinnyMind** [comment]
Thanks for opening the issue! I'll rewrite the way lookup is performed.

**Comment by EbenZhang** [comment]
works fine now with 1.2.2. Thanks for the fix.
