### ISSUE TITLE
Does ssh work on windows platform?

### ISSUE THREAD

**Issue by vik-borisov** [SkinnyMind/libgit2dart#84]
I had some problems with SSH tests on the Windows platform.
Could you clarify for me, is it my fault or the restriction of the library?

- https://github.com/SkinnyMind/libgit2dart/blob/b66662f33cfbe2fd4881f63775fa44ae12961afa/test/credentials_test.dart#L86
- https://github.com/SkinnyMind/libgit2dart/blob/b66662f33cfbe2fd4881f63775fa44ae12961afa/test/credentials_test.dart#L188
- https://github.com/SkinnyMind/libgit2dart/blob/b66662f33cfbe2fd4881f63775fa44ae12961afa/test/credentials_test.dart#L215

**Comment by SkinnyMind** [comment]
Hi, ssh does work on windows, you have to make sure that there is libssh2 built on your system and `libssh2.dll` is somewhere in the path, or in system path (e.g. "Windows\System32").
